# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e60849c56455085e50897db387beb591d7ee29a8292a00fb4717a3ead1759529dacf53239d6146b4352245fe1c1981d1d21a9ffe69ffbe9180e1707c0a54ab3

test:
  secret_key_base: 6928b630220457d32e9c76ae65ff7f832e5f027d4872d0da78c564d26fa6b0eb3d572900ca27ae8f96ce9d07b8d6404a71b73f8ebdbdc03f56c245325909d57a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
